Move Command to RBUI
PhlexUI/phlex_ui pull request #122
Opened 2024-09-06 00:17 UTC by jacksonpires

2024-09-06 12:04 UTC, pierry01 commented on lib/rbui/command/command_controller.js
> +// Connects to data-controller="command"
`rbui--command`

2024-09-06 12:07 UTC, pierry01 approved these changes
perfect!

2024-09-06 14:46 UTC, pierry01 approved these changes

2024-09-06 15:11 UTC, cirdes requested changes

2024-09-06 15:11 UTC, cirdes commented on lib/rbui/command/command_input.rb
> +        data_action: "input->rbui--command#filter keydown.down->rbui--command#handleKeydown keydown.up->rbui--command#handleKeydown keydown.enter->rbui--command#handleKeydown keydown.esc->rbui--dialo
@jacksonpires, we should isolate the JS controller. `rbui--dialog` is being referenced here. You should implement the dismiss action inside the command component.

2024-09-09 11:52 UTC, cirdes approved these changes

2024-09-09 11:53 UTC, merged