Add pagination components
PhlexUI/phlex_ui pull request #35
Opened 2024-03-09 22:16 UTC by schodevio

2024-03-09 22:35 UTC, iseth commented
Hey just push a fix for standard rb. Could you merge it into your branch and repush.

2024-03-09 22:57 UTC, iseth requested changes
Everything looks good but could maybe you could change that one change.

2024-03-09 22:57 UTC, iseth commented on lib/phlex_ui/pagination/page.rb
> +        )
this should be using the default button class you get them like this:
```ruby
PhlexUI::Button.new(variant: :secondary).attrs[:class]
```
also might be good to structure it like they do here:
https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/pagination.tsx#L52

have the active class the outline and active class the ghost variant, you should be able to get them with the above method.

2024-03-09 22:57 UTC, iseth commented on lib/phlex_ui/pagination/page.rb
> +        )
Just do not want to clutter the file with classes and when we ever update the button class it will reflect there

2024-03-09 22:58 UTC, iseth commented
Also run `bundle exec standardrb --fix` to fix the standard rb

2024-03-10 00:46 UTC, merged

2024-03-10 12:12 UTC, schodevio commented
@iseth Thanks!